baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'The Cloud Theory'
theme = "slick"

[params]
    # Site subtitle (not shown if commented out or set to false)
    subtitle = "Technical blog"

    # Site description
    description = "The Cloud Theory - technical blog"

    # Favicon file (relative to baseURL - place below static or assets folder)
    favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static or assets folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # If false the RSS link in footer is not shown
    showRssLink = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = false

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the title, dates and taxonomy are not shown on single view
    showMeta = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"